### ISSUE TITLE
Export in HTML failed in windows

### ISSUE THREAD

**Issue by arita37** [datapane/datapane#31] opened 2020-10-26 12:17 UTC
**Describe the bug**
   in python code , it fails

```
import pandas as pd
import altair as alt
import datapane as dp

dataset = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')
df = dataset.groupby(['continent', 'date'])['new_cases_smoothed_per_million'].mean().reset_index()

plot = alt.Chart(df).mark_area(opacity=0.4, stroke='black').encode(
    x='date:T',
    y=alt.Y('new_cases_smoothed_per_million:Q', stack=None),
    color=alt.Color('continent:N', scale=alt.Scale(scheme='set1')),
    tooltip='continent:N'
).interactive().properties(width='container')

dp.Report(
    dp.Plot(plot), 
    dp.Table(df)
).save(path='report.html', open=True)
```

 due to jinja cannot find Path.
Maybe, due to windows path.

**Comment by arita37** [comment] 2020-10-28 00:32
Thanks.
Many, many of users are on windows...

Error was related to jinja and “cannot find path”.

Anyway this is an excellent initiative,
Keep it simple and run many tests to ensure
basic usability, 
many people will use it.

**Comment by ethanlarochelle** [comment] 2020-12-09 13:34
Hi all, I've been dabbling with Datapane at work over the last month or so. Just as an additional data-point I am able to run the above example using Windows 10 Python 3.8.5 installed in a virtualenv.  Here is a truncated output of pip list:
Package             Version
------------------- ---------
altair              4.1.0
bokeh               2.2.1
datapane            0.8.0
ipykernel           5.3.4
ipython             7.16.1
Jinja2              2.11.2
jupyter-client      6.1.6
jupyter-core        4.6.3
jupyterlab          2.2.2
MarkupSafe          1.1.1
matplotlib          3.3.0
notebook            6.0.3
numpy               1.19.1
openpyxl            3.0.4
pandas              1.0.5
pandocfilters       1.4.2
pip                 20.2.1
plotly              4.11.0
pywin32             228
pywinpty            0.5.7
pyzmq               19.0.1
tabulate            0.8.7
vega-datasets       0.8.0
xlrd                1.2.0

**Comment by mands** [comment] 2021-01-04 17:13
Thanks for the confirmation @ethanlarochelle , closing as can't reproduce on a conda install on Windows 10. 
Please let me know / reopen if you still see the problem.

**Closed by mands** 2021-01-04 17:13 UTC
