### ISSUE TITLE
Not able to re

### ISSUE THREAD

**Issue by iGSRi** [datapane/datapane#83] opened 2021-02-10 09:45 UTC
**While executing below code:**

import pandas as pd
import altair as alt
import datapane as dp

df = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/GOOG?period2=1585222905&interval=1mo&events=history')

chart = alt.Chart(df).encode(
    x='Date:T',
    y='Open'
).mark_line().interactive()

r = dp.Report(dp.DataTable(df), dp.Plot(chart))
r.save(path='report.html', open=True)

**Getting error:**
ValueError: No objects to concatenate

ValueError                                Traceback (most recent call last)
<ipython-input-28-f005ecca2f7b> in <module>
     10 ).mark_line().interactive()
     11 
---> 12 r = dp.Report(dp.DataTable(df), dp.Plot(chart))

**Comment by mands** [comment] 2021-02-10 10:39
Can you provide the full error/stacktrace?

**Comment by mands** [comment] 2021-02-10 10:42
I've just ran your code locally on my machine (using Datapane 0.9.2 on Python 3.8 under Linux) and can not reproduce the issue - perhaps there was an error in downloading the csv file.

**Comment by mands** [comment] 2021-03-04 19:16
closing as can't reproduce - please feel free to open if you have more info/issues

**Closed by mands** 2021-03-04 19:16 UTC
Labels: question
