### ISSUE TITLE
Binary columns rendered as boolean values

### ISSUE THREAD

**Issue by tr31zh** [datapane/datapane#274] opened 2022-09-02 07:51 UTC
### System Information
- OS: MacOS 12.5.1
- Python version: 3.10.6
- Python environment: pip
- Using jupyter: true
- Datapane version: 0.15.0

### Bug / Issue

When using dataframes, binary columns are rendrered as boolean values
ex: 

`
dp.DataTable(
      pd.DataFrame(
          {
              1: [1, 0, 0, 1],
              2: [1, 0, 0, 1],
              3: [1, 0, 0, 1],
              4: [1, 0, 0, 1],
              5: [1, 0, 0, 1],
              6: [1, 0, 0, 1],
          }
      )
  )
`
Will be rendered as:
1         2         ...
True  True     ...
False  False. ...

**Comment by shahinrostami** [comment] 2022-09-02 08:02
Hey @tr31zh !  Thank you for raising this. It looks like it may be a result of a recent update that included this PR. https://github.com/datapane/datapane/pull/256.

@mands although it's an optimisation feature, we may need to re-think it the outcome is undesirable!

**Comment by mands** [comment] 2022-09-02 08:36
@shahinrostami agreed, yes let's disable this optimisation and do a patch release. I assume the integer optimisation will kick in anyway and it will store these as `uint8` anyway which is still a size saving

**Comment by shahinrostami** [comment] 2022-09-06 12:22
Just a heartbeat to confirm that I'll be picking this one up today 👍

**Comment by shahinrostami** [comment] 2022-09-06 16:45
Pending a review, this fix should make it into our release! I'll label this issue as `release pending` for now.

**Comment by shahinrostami** [comment] 2022-09-07 14:37
Re-opening until the fix makes it into a release

**Comment by shahinrostami** [comment] 2022-09-22 18:21
Hey @tr31zh - this should have been fixed in the recent release! I've confirmed it with the example:

```python
import datapane as dp
import pandas as pd

app = dp.App(
    dp.DataTable(
        pd.DataFrame(
            {
                1: [1, 0, 0, 1],
                2: [1, 0, 0, 1],
                3: [1, 0, 0, 1],
                4: [1, 0, 0, 1],
                5: [1, 0, 0, 1],
                6: [1, 0, 0, 1],
            }
        )
    )
).save("test.html")
```

<img width="1413" alt="Screenshot 2022-09-22 at 19 21 23" src="https://user-images.githubusercontent.com/15690380/191822585-f25e0975-1a9e-4b6c-baa0-d146b10e3079.png">

Thank you for raising this – please let us know if there's anything else!

**Closed by shahinrostami** 2022-09-22 18:21 UTC
Labels: release pending

**Comment by tr31zh** [comment] 2022-09-23 12:58
Hi @shahinrostami ,
I've just checked, everything looks fine.
Thank you!

**Comment by shahinrostami** [comment] 2022-09-23 13:12
> Hi @shahinrostami ,
> I've just checked, everything looks fine.
> Thank you!

Perfect, happy to hear it!
