### ISSUE TITLE
DataTable inducing erratic rounding off for decimal values

### ISSUE THREAD

**Issue by VivekDehariya** [datapane/datapane#209] opened 2022-06-12 18:26 UTC
### System Information

- OS: Windows 10
- Python version: 3.10.5
- Python environment: pip
- Using jupyter: false
- Datapane version: 0.14.0

### Bug / Issue

Using a DataTable object inside a report rounds off the values completely wrongly. This is not the case when using a Table object or adding an Attachment with the same dataframe object, the values are correct while using any of these.

For instance:  691355.0 becomes 691400, 769358.78 becomes 769400. This is completely unusable.

#159

**Comment by VivekDehariya** [comment] 2022-06-13 20:29
Thanks a lot for the quick addressal, @shahinrostami. Please let me know if there's any version upgrade command that would be required to be run for the fix to be available.

**Comment by shahinrostami** [comment] 2022-06-14 11:16
Hi @VivekDehariya! We've just reviewed the update - we'll let you know and close the issue when it's live!

**Comment by shahinrostami** [comment] 2022-09-06 10:27
Hey @VivekDehariya ! Thanks again for raising this. I'm happy to say the fix has made it into the recent release, and I've confirmed that it works as intended:

<img width="669" alt="Screenshot 2022-09-06 at 11 26 01" src="https://user-images.githubusercontent.com/15690380/188612281-39afc8f7-94f7-4aa6-a5e0-b2af613c582f.png">

Please let us know if there's anything else!

**Closed by shahinrostami** 2022-09-06 10:27 UTC
Labels: bug, release pending
