### ISSUE TITLE
ValueError: too many values to unpack (expected 2) when showing a DataTable in Jupyter

### ISSUE THREAD

**Issue by jperez-dx** [datapane/datapane#353] opened 2023-03-01 15:56 UTC
I'm getting the error shown below when running the following cell in Jupyter:
```
dp.DataTable(pandas_df)
```

<details><summary>Trace</summary>

<p>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /opt/conda/lib/python3.9/site-packages/IPython/core/formatters.py:920, in IPythonDisplayFormatter.__call__(self, obj)
    918 method = get_real_method(obj, self.print_method)
    919 if method is not None:
--> 920     method()
    921     return True

File /opt/conda/lib/python3.9/site-packages/datapane/blocks/base.py:94, in BaseBlock._ipython_display_(self)
     91 from datapane.view import Blocks
     93 if get_environment().support_rich_display:
---> 94     html_str = stringify_report(Blocks(self))
     95     display(HTML(html_str))
     96 else:

File /opt/conda/lib/python3.9/site-packages/datapane/processors/api.py:126, in stringify_report(blocks, name, formatting)
    116 """Stringify the app document to a HTML string
    117 
    118 Args:
   (...)
    121     formatting: Sets the basic app styling
    122 """
    124 s = ViewState(blocks=Blocks.wrap_blocks(blocks), file_entry_klass=B64FileEntry)
    125 report_html: str = (
--> 126     Pipeline(s)
    127     .pipe(PreProcessView())
    128     .pipe(ConvertXML())
    129     .pipe(ExportHTMLStringInlineAssets(name=name, formatting=formatting))
    130     .result
    131 )
    133 return report_html

File /opt/conda/lib/python3.9/site-packages/datapane/processors/types.py:59, in Pipeline.pipe(self, p)
     57 def pipe(self, p: BaseProcessor[P_IN, P_OUT]) -> Pipeline[P_OUT]:
     58     p.s = self._state
---> 59     y = p.__call__(self._x)  # need to call as positional args
     60     self._state = p.s
     61     return Pipeline(self._state, y)

File /opt/conda/lib/python3.9/site-packages/datapane/processors/processors.py:90, in ConvertXML.__call__(self, _)
     89 def __call__(self, _: t.Any) -> ElementT:
---> 90     initial_doc = self.convert_xml()
     91     transformed_doc = self.post_transforms(initial_doc)
     93     # convert to string

File /opt/conda/lib/python3.9/site-packages/datapane/processors/processors.py:107, in ConvertXML.convert_xml(self)
    104 def convert_xml(self) -> ElementT:
    105     # create initial state
    106     builder_state = XMLBuilder(store=self.s.store)
--> 107     self.s.blocks.accept(builder_state)
    108     return builder_state.get_root(self.fragment)

File /opt/conda/lib/python3.9/site-packages/datapane/blocks/base.py:100, in BaseBlock.accept(self, visitor)
     99 def accept(self, visitor: VV) -> VV:
--> 100     visitor.visit(self)
    101     return visitor

File /opt/conda/lib/python3.9/site-packages/multimethod/__init__.py:315, in multimethod.__call__(self, *args, **kwargs)
    313 func = self[tuple(func(arg) for func, arg in zip(self.type_checkers, args))]
    314 try:
--> 315     return func(*args, **kwargs)
    316 except TypeError as ex:
    317     raise DispatchError(f"Function {func.__code__}") from ex

File /opt/conda/lib/python3.9/site-packages/datapane/view/xml_visitor.py:88, in XMLBuilder.visit(self, b)
     86 @multimethod
     87 def visit(self, b: Blocks) -> XMLBuilder:
---> 88     sub_elements = self._visit_subnodes(b)
     90     # Blocks are converted to Group internally
     91     element = E.Group(*sub_elements, columns="1", valign="top")

File /opt/conda/lib/python3.9/site-packages/datapane/view/xml_visitor.py:73, in XMLBuilder._visit_subnodes(self, b)
     71 cur_elements = self.elements
     72 self.elements = []
---> 73 b.traverse(self)  # visit subnodes
     74 res = self.elements
     75 self.elements = cur_elements

File /opt/conda/lib/python3.9/site-packages/datapane/blocks/layout.py:70, in ContainerBlock.traverse(self, visitor)
     68 def traverse(self, visitor: VV) -> VV:
     69     # perform a depth-first traversal of the contained blocks
---> 70     return reduce(lambda _visitor, block: block.accept(_visitor), self.blocks, visitor)

File /opt/conda/lib/python3.9/site-packages/datapane/blocks/layout.py:70, in ContainerBlock.traverse.<locals>.<lambda>(_visitor, block)
     68 def traverse(self, visitor: VV) -> VV:
     69     # perform a depth-first traversal of the contained blocks
---> 70     return reduce(lambda _visitor, block: block.accept(_visitor), self.blocks, visitor)

File /opt/conda/lib/python3.9/site-packages/datapane/blocks/base.py:100, in BaseBlock.accept(self, visitor)
     99 def accept(self, visitor: VV) -> VV:
--> 100     visitor.visit(self)
    101     return visitor

File /opt/conda/lib/python3.9/site-packages/multimethod/__init__.py:315, in multimethod.__call__(self, *args, **kwargs)
    313 func = self[tuple(func(arg) for func, arg in zip(self.type_checkers, args))]
    314 try:
--> 315     return func(*args, **kwargs)
    316 except TypeError as ex:
    317     raise DispatchError(f"Function {func.__code__}") from ex

File /opt/conda/lib/python3.9/site-packages/datapane/view/xml_visitor.py:127, in XMLBuilder.visit(self, b)
    124 @multimethod
    125 def visit(self, b: AssetBlock):
    126     """Main XMl creation method - visitor method"""
--> 127     fe = self._add_asset_to_store(b)
    129     _E = getattr(E, b._tag)
    131     e: etree._Element = _E(
    132         type=fe.mime,
    133         # size=conv_attrib(fe.size),
   (...)
    137         src=f"ref://{fe.hash}",
    138     )

File /opt/conda/lib/python3.9/site-packages/datapane/view/xml_visitor.py:164, in XMLBuilder._add_asset_to_store(self, b)
    162     meta: AssetMeta = writer.get_meta(b.data)
    163     fe = self.store.get_file(meta.ext, meta.mime)
--> 164     writer.write_file(b.data, fe.file)
    165     self.store.add_file(fe)
    166 except DispatchError:

File /opt/conda/lib/python3.9/site-packages/multimethod/__init__.py:315, in multimethod.__call__(self, *args, **kwargs)
    313 func = self[tuple(func(arg) for func, arg in zip(self.type_checkers, args))]
    314 try:
--> 315     return func(*args, **kwargs)
    316 except TypeError as ex:
    317     raise DispatchError(f"Function {func.__code__}") from ex

File /opt/conda/lib/python3.9/site-packages/datapane/view/asset_writers.py:87, in DataTableWriter.write_file(self, x, f)
     85     raise DPClientError("Empty DataFrame provided")
     86 # process_df called in Arrow.save_file
---> 87 ArrowFormat.save_file(f, df)

File /opt/conda/lib/python3.9/site-packages/datapane/common/datafiles.py:63, in ArrowFormat.save_file(fn, df)
     61 df = process_df(df)
     62 # NOTE - can pass expected schema and columns for output df here
---> 63 table: pa.Table = pa.Table.from_pandas(df, preserve_index=False)
     64 write_table(table, fn)

File /opt/conda/lib/python3.9/site-packages/pyarrow/table.pxi:1553, in pyarrow.lib.Table.from_pandas()

ValueError: too many values to unpack (expected 2)
```

</p>

</details>

```
!pip install datapane
```
<details><summary>pip output</summary>
<p>

```
Requirement already satisfied: pyngrok<6.0.0,>=5.2.1 in /opt/conda/lib/python3.9/site-packages (from datapane) (5.2.1)
Requirement already satisfied: boltons<22.0.0,>=20.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (21.0.0)
Requirement already satisfied: cheroot<10.0.0,>=9.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (9.0.0)
Requirement already satisfied: pyarrow<11.0.0,>=6.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (10.0.1)
Requirement already satisfied: altair<5.0.0,>=4.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (4.2.1)
Requirement already satisfied: dulwich<0.22.0,>=0.20.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.21.3)
Requirement already satisfied: furl<3.0.0,>=2.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (2.1.3)
Requirement already satisfied: datacommons<2.0.0,>=1.4.3 in /opt/conda/lib/python3.9/site-packages (from datapane) (1.4.3)
Requirement already satisfied: requests-toolbelt<0.11.0,>=0.9.1 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.10.1)
Requirement already satisfied: dacite<2.0.0,>=1.0.2 in /opt/conda/lib/python3.9/site-packages (from datapane) (1.8.0)
Requirement already satisfied: vega-datasets<1.0.0,>=0.9.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.9.0)
Requirement already satisfied: click<9.0.0,>=7.1.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (8.1.3)
Requirement already satisfied: click-spinner<0.2.0,>=0.1.8 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.1.10)
Requirement already satisfied: dominate<3.0.0,>=2.4.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (2.7.0)
Requirement already satisfied: toolz<0.13.0,>=0.11.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.12.0)
Requirement already satisfied: pandas<2.0.0,>=1.1.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (1.5.3)
Requirement already satisfied: lxml<5.0.0,>=4.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (4.9.2)
Requirement already satisfied: micawber>=0.5.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.5.4)
Requirement already satisfied: colorlog<7.0.0,>=4.1.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (6.7.0)
Requirement already satisfied: datacommons-pandas<0.0.4,>=0.0.3 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.0.3)
Requirement already satisfied: glom<24.0.0,>=22.1.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (23.1.1)
Requirement already satisfied: requests<3.0.0,>=2.19.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (2.28.2)
Requirement already satisfied: jsonschema<5.0.0,>=3.2.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (4.17.3)
Requirement already satisfied: multimethod<2.0,>=1.9 in /opt/conda/lib/python3.9/site-packages (from datapane) (1.9.1)
Requirement already satisfied: nbconvert>=5.6.1 in /opt/conda/lib/python3.9/site-packages (from datapane) (7.2.9)
Requirement already satisfied: chardet<6.0.0,>=4.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (5.1.0)
Requirement already satisfied: tabulate<0.10.0,>=0.8.9 in /opt/conda/lib/python3.9/site-packages (from datapane) (0.9.0)
Requirement already satisfied: importlib_resources<6.0.0,>=3.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (5.12.0)
Requirement already satisfied: ipynbname<2022.0.0,>=2021.3.2 in /opt/conda/lib/python3.9/site-packages (from datapane) (2021.3.2)
Requirement already satisfied: posthog<3.0.0,>=1.4.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (2.3.1)
Requirement already satisfied: PyYAML<7.0.0,>=5.4.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (6.0)
Requirement already satisfied: packaging<24.0.0,>=21.0.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (23.0)
Requirement already satisfied: pydantic<2.0.0,>=1.6.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (1.10.5)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /opt/conda/lib/python3.9/site-packages (from datapane) (4.4.0)
Requirement already satisfied: entrypoints in /opt/conda/lib/python3.9/site-packages (from altair<5.0.0,>=4.0.0->datapane) (0.4)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.9/site-packages (from altair<5.0.0,>=4.0.0->datapane) (3.1.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.9/site-packages (from altair<5.0.0,>=4.0.0->datapane) (1.23.5)
Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.9/site-packages (from cheroot<10.0.0,>=9.0.0->datapane) (1.16.0)
Requirement already satisfied: more-itertools>=2.6 in /opt/conda/lib/python3.9/site-packages (from cheroot<10.0.0,>=9.0.0->datapane) (9.1.0)
Requirement already satisfied: jaraco.functools in /opt/conda/lib/python3.9/site-packages (from cheroot<10.0.0,>=9.0.0->datapane) (3.6.0)
Requirement already satisfied: urllib3>=1.25 in /opt/conda/lib/python3.9/site-packages (from dulwich<0.22.0,>=0.20.0->datapane) (1.25.11)
Requirement already satisfied: orderedmultidict>=1.0.1 in /opt/conda/lib/python3.9/site-packages (from furl<3.0.0,>=2.0.0->datapane) (1.0.1)
Requirement already satisfied: face==20.1.1 in /opt/conda/lib/python3.9/site-packages (from glom<24.0.0,>=22.1.0->datapane) (20.1.1)
Requirement already satisfied: attrs in /opt/conda/lib/python3.9/site-packages (from glom<24.0.0,>=22.1.0->datapane) (22.2.0)
Requirement already satisfied: zipp>=3.1.0 in /opt/conda/lib/python3.9/site-packages (from importlib_resources<6.0.0,>=3.0.0->datapane) (3.15.0)
Requirement already satisfied: ipykernel in /opt/conda/lib/python3.9/site-packages (from ipynbname<2022.0.0,>=2021.3.2->datapane) (6.21.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/conda/lib/python3.9/site-packages (from jsonschema<5.0.0,>=3.2.0->datapane) (0.19.3)
Requirement already satisfied: pygments>=2.4.1 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (2.14.0)
Requirement already satisfied: traitlets>=5.0 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (5.9.0)
Requirement already satisfied: markupsafe>=2.0 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (2.1.2)
Requirement already satisfied: importlib-metadata>=3.6 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (6.0.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (1.5.0)
Requirement already satisfied: nbformat>=5.1 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (5.7.3)
Requirement already satisfied: nbclient>=0.5.0 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (0.7.2)
Requirement already satisfied: bleach in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (6.0.0)
Requirement already satisfied: tinycss2 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (1.2.1)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (4.11.2)
Requirement already satisfied: mistune<3,>=2.0.3 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (2.0.5)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (0.2.2)
Requirement already satisfied: jupyter-core>=4.7 in /opt/conda/lib/python3.9/site-packages (from nbconvert>=5.6.1->datapane) (5.2.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas<2.0.0,>=1.1.0->datapane) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.9/site-packages (from pandas<2.0.0,>=1.1.0->datapane) (2.8.2)
Requirement already satisfied: backoff>=1.10.0 in /opt/conda/lib/python3.9/site-packages (from posthog<3.0.0,>=1.4.0->datapane) (2.2.1)
Requirement already satisfied: monotonic>=1.5 in /opt/conda/lib/python3.9/site-packages (from posthog<3.0.0,>=1.4.0->datapane) (1.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.19.0->datapane) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.19.0->datapane) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.19.0->datapane) (2.8)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/lib/python3.9/site-packages (from jupyter-core>=4.7->nbconvert>=5.6.1->datapane) (3.0.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/conda/lib/python3.9/site-packages (from nbclient>=0.5.0->nbconvert>=5.6.1->datapane) (8.0.3)
Requirement already satisfied: fastjsonschema in /opt/conda/lib/python3.9/site-packages (from nbformat>=5.1->nbconvert>=5.6.1->datapane) (2.16.3)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.9/site-packages (from beautifulsoup4->nbconvert>=5.6.1->datapane) (2.4)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.9/site-packages (from bleach->nbconvert>=5.6.1->datapane) (0.5.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.1.6)
Requirement already satisfied: psutil in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (5.9.4)
Requirement already satisfied: debugpy>=1.6.5 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (1.6.6)
Requirement already satisfied: comm>=0.1.1 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.1.2)
Requirement already satisfied: tornado>=6.1 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (6.2)
Requirement already satisfied: pyzmq>=20 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (25.0.0)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (1.5.6)
Requirement already satisfied: ipython>=7.23.1 in /opt/conda/lib/python3.9/site-packages (from ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (8.11.0)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (3.0.38)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.7.5)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.6.2)
Requirement already satisfied: backcall in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (4.8.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.18.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/lib/python3.9/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.9/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.9/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.6)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (2.2.1)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (1.2.0)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel->ipynbname<2022.0.0,>=2021.3.2->datapane) (0.2.2)
Installing collected packages: datapane
Successfully installed datapane-0.16.1
```

</p>
</details>

**Comment by shahinrostami** [comment] 2023-03-01 16:49
Hi @jperez-dx, thank you for raising this! A few questions to help us understand the issue:

- Are you on the latest version of Datapane (`0.16.1`)?
- Can you share more information about the DataFrame `pandas_df`? I've seen a similar error when passing in a Series or MultiIndex.
- Does the following code produce the same error?

```python
import datapane as dp
from vega_datasets import data

dp.DataTable(data.iris())
```

**Comment by jperez-dx** [comment] 2023-03-01 17:01
Hi @shahinrostami!

- Yes, I'm using `0.16.1`. You can see the versions of all dependencies in the pip output I shared in the description
- Sure! See below
- Yes, getting the same error when running that snippet

![image](https://user-images.githubusercontent.com/23344151/222209923-3e80ef3a-25d3-40b7-83bd-fa307f555c9f.jpg)

**Comment by shahinrostami** [comment] 2023-03-18 18:45
Thanks @jperezr21. I'm going to ping the rest of the team on this as I'm not able to reproduce it. In the meantime, if you have any ideas, e.g. some unique environment setup, please let us know.

**Comment by mands** [comment] 2023-04-07 10:55
Closing as can't reproduce - please reopen if you still hit the issue

**Closed by mands** 2023-04-07 10:55 UTC
